// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsvyoswgukdgpqvbwrfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhzdnlvc3dndWtkZ3BxdmJ3cmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MjAzOTIsImV4cCI6MjA2MjE5NjM5Mn0.oeYBqLmr7hKeReNCTDnG67gtsNMlKjj9VZnuypOnB00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);